apiVersion: skaffold/v2alpha3
kind: Config
build:
  artifacts:
    - image: akthrms/practice-skaffold
      docker:
        dockerfile: ./Dockerfile
  tagPolicy:
    dateTime: {}
  local:
    push: true
deploy:
  kubectl:
    manifests:
      - practice-skaffold-*
